### ISSUE TITLE
Bot not working in personal scope(group chat)

### ISSUE THREAD

**Issue by v-shakin** [engagesquared/TeamsHistoryManagementApp#1]
Deployed the bot, It seems to be working in channel. But it throws an exception while using in personal chat.
When I debugged the code, graph api is giving correct response for top 50 chats in personal scope, but for the nextLink(using skip token) it is throwing BadRequest response exception.
Can you help in fixing that.

**Comment by engagesquared** [comment]
Just tested, looks like it is a Graph API internal bug
I reproduced it in graph explorer.
Request to the url from @odata.nextLink  always returns “Bad request” in beta/chats/ endpoint
No workaround for it, because it is only available in beta.

1st request:
![1](https://user-images.githubusercontent.com/59990977/91416402-03fe8780-e858-11ea-82e9-fea3c80d439d.png)

2nd request to the nextLink from previous:
![2](https://user-images.githubusercontent.com/59990977/91416413-07920e80-e858-11ea-8b74-3ec28485b36a.png)

I suggest to open an issue for MS Graph API
